### ISSUE TITLE
Implement enemy AI

### ISSUE THREAD

**Issue by Reshlynt** [SCCapstone/BrickThrowers#28]
Players should be expected to encounter enemies during an expedition. All enemies should incur damage aganist a player diver when their colliders are in contact with each other. Each enemy should have a unique behavior.

```[tasklist]
### Tasks
- [ ] https://github.com/SCCapstone/BrickThrowers/issues/27
- [ ] https://github.com/SCCapstone/BrickThrowers/issues/29
- [ ] https://github.com/SCCapstone/BrickThrowers/issues/30
- [ ] https://github.com/SCCapstone/BrickThrowers/issues/31
- [ ] https://github.com/SCCapstone/BrickThrowers/issues/32
- [ ] https://github.com/SCCapstone/BrickThrowers/issues/33
- [ ] https://github.com/SCCapstone/BrickThrowers/issues/34
```
